package martekstaj;

import java.awt.Image;
import java.sql.Statement;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class yoneticiIslemleri extends javax.swing.JFrame {
    
    String hostname = "localhost";
    String sqlInstanceName = "LAPTOP-KT3GSJ4P"; // Bilgisayar adı
    String sqlDatabase = "martekstaj";  // SQL Server veritabanı adı
    String sqlUser = "sa";
    String sqlPassword = "sasa"; // sa hesabının parolası

    public yoneticiIslemleri() {
        initComponents();
        ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgTaramasi = new javax.swing.JButton();
        jButtonEkle = new javax.swing.JButton();
        jTextFieldHostAddressEkleme = new javax.swing.JTextField();
        jButtonSifirla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCihazIpTarama = new javax.swing.JButton();
        jLabelCihazinIPAdresi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAgaBagliCihazlar = new javax.swing.JTable();
        jTextFieldHostNameEkleme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPingAtma = new javax.swing.JTextField();
        jButtonPingAta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAgTaramasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAgTaramasi.setText("Ağ Taraması");
        jButtonAgTaramasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgTaramasiActionPerformed(evt);
            }
        });

        jButtonEkle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEkle.setText("Ekle");
        jButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkleActionPerformed(evt);
            }
        });

        jTextFieldHostAddressEkleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHostAddressEklemeActionPerformed(evt);
            }
        });

        jButtonSifirla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSifirla.setText("Sıfırla");
        jButtonSifirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSifirlaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Ağa Bağlı Cihazlar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cihazımın IP Adresi:");

        jButtonCihazIpTarama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCihazIpTarama.setText("Tara");
        jButtonCihazIpTarama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCihazIpTaramaActionPerformed(evt);
            }
        });

        jLabelCihazinIPAdresi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCihazinIPAdresi.setText("*************");

        jTableAgaBagliCihazlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HostAddress", "HostName"
            }
        ));
        jScrollPane2.setViewportView(jTableAgaBagliCihazlar);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("HostAddress:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("HostName:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Ping Atanacak IP:");

        jTextFieldPingAtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPingAtmaActionPerformed(evt);
            }
        });

        jButtonPingAta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPingAta.setText("OK");
        jButtonPingAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPingAtaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCihazinIPAdresi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCihazIpTarama, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldHostAddressEkleme)
                                    .addComponent(jTextFieldHostNameEkleme, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonSifirla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAgTaramasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldPingAtma, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPingAta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCihazinIPAdresi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCihazIpTarama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAgTaramasi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSifirla, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHostAddressEkleme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHostNameEkleme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addComponent(jButtonEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPingAtma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPingAta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgTaramasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgTaramasiActionPerformed
        try {
            // agTaramasi sinifindan nesne olustuldu
            agTaramasi ag = new agTaramasi();

            // agTaramasi sinifinin main metodu cagridi
            ag.main(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            // JDBC sürücüsünü yükle
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            // Veritabanina baglanti URL si olusturulur
            String connectURL = "jdbc:sqlserver://" + hostname + ":1433"
                    + ";instance=" + sqlInstanceName + ";databaseName=" + sqlDatabase;

            // Bağlanti acilir
            Connection conn = DriverManager.getConnection(connectURL, sqlUser, sqlPassword);
            // System.out.println("Veritabanına başarıyla bağlandı!");

            // SQL sorgusu 
            String sql = "SELECT * FROM agTaramaSQL";

            // Sorguyu calistir ve sonucu al
            Statement st = conn.createStatement();
            ResultSet resultSet = st.executeQuery(sql);

            // veritabanindan gelen her satiri JTable'a ekler
            while (resultSet.next()) {
                String hostAddress = resultSet.getString("HostAddress");
                String hostName = resultSet.getString("HostName");
                
                String tbData[] = {hostAddress, hostName};
                DefaultTableModel tblModel = (DefaultTableModel) jTableAgaBagliCihazlar.getModel();
                tblModel.addRow(tbData);
            }
            // Bağlantıyı kapat
            conn.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonAgTaramasiActionPerformed

    private void jButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkleActionPerformed
        try {
            // JDBC sürücüsünü yükle
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            // Veritabanina baglanti URL si olusturulur
            String connectURL = "jdbc:sqlserver://" + hostname + ":1433"
                    + ";instance=" + sqlInstanceName + ";databaseName=" + sqlDatabase;

            // Bağlanti acilir
            Connection conn = DriverManager.getConnection(connectURL, sqlUser, sqlPassword);
            // System.out.println("Veritabanına basariyla baglandi!");

            // SQL sorgusu // veritabanina veri ekler
            String sql = "INSERT INTO agTaramaSQL (HostAddress, HostName) VALUES (?, ?)";

            // Sorguyu calistir ve sonucu al
            Statement st = conn.createStatement();
            PreparedStatement preparedStatement = conn.prepareStatement(sql);

            //  JTextField'lardan grirlen veriyi alir
            preparedStatement.setString(1, jTextFieldHostAddressEkleme.getText());
            preparedStatement.setString(2, jTextFieldHostNameEkleme.getText());
            
            int affectedRows = preparedStatement.executeUpdate();

            // Baglantiyi kapat    
            conn.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        // yeni veriler JTable a eklenir
        DefaultTableModel model = (DefaultTableModel) jTableAgaBagliCihazlar.getModel();
        model.addRow(new Object[]{jTextFieldHostAddressEkleme.getText(), jTextFieldHostNameEkleme.getText()});
        jTextFieldHostAddressEkleme.setText("");
        jTextFieldHostNameEkleme.setText("");
    }//GEN-LAST:event_jButtonEkleActionPerformed

    private void jButtonCihazIpTaramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCihazIpTaramaActionPerformed
        
        try {
            // agTaramasi class indaki cihazIpAdresim() metodu calistirildi
            agTaramasi.cihazIpAdresim();
            //jLabelCihazinIPAdresi icine IP adresini yazdir
            jLabelCihazinIPAdresi.setText(agTaramasi.getBilgisayarIp());
        } catch (UnknownHostException ex) {
            Logger.getLogger(yoneticiIslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButtonCihazIpTaramaActionPerformed

    private void jButtonSifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSifirlaActionPerformed
        try {
            // JDBC sürücüsünü yükle
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            // Veritabanina baglanti URL si olusturulur
            String connectURL = "jdbc:sqlserver://" + hostname + ":1433"
                    + ";instance=" + sqlInstanceName + ";databaseName=" + sqlDatabase;

            // baglantiyi ac
            Connection conn = DriverManager.getConnection(connectURL, sqlUser, sqlPassword);
            // SQL sorgusu  // veritabanindaki tüm verileri siler
            String sql = "DELETE FROM agTaramaSQL";
            Statement st = conn.createStatement();
            int affectedRows = st.executeUpdate(sql);
            conn.close();

            //tablodaki verileri 0'lar
            DefaultTableModel model = (DefaultTableModel) jTableAgaBagliCihazlar.getModel();
            model.setRowCount(0);
            
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButtonSifirlaActionPerformed

    private void jTextFieldHostAddressEklemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHostAddressEklemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHostAddressEklemeActionPerformed

    private void jTextFieldPingAtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPingAtmaActionPerformed

    }//GEN-LAST:event_jTextFieldPingAtmaActionPerformed

    private void jButtonPingAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPingAtaActionPerformed
        pingAtma ping = new pingAtma();
        String hedefAdres = jTextFieldPingAtma.getText(); // jTextFieldPingAtma icindeki metni al
        ping.pingAt(hedefAdres); // pingAt metoduna hedefAdres iletilir

        boolean erisilemez = !pingAtma.pingAt(hedefAdres); // pingAt metodundan donen deger kullanilir

        if (erisilemez) {
            JOptionPane.showMessageDialog(null, "Hedef adrese erişilemiyor. Mail adresini kontrol ediniz.");
        } else {
            // Hedefe erisilirse
            JOptionPane.showMessageDialog(null, "Hedef adrese erişildi.");
        }
        jTextFieldPingAtma.setText("");
    }//GEN-LAST:event_jButtonPingAtaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yoneticiIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yoneticiIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yoneticiIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yoneticiIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yoneticiIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgTaramasi;
    private javax.swing.JButton jButtonCihazIpTarama;
    private javax.swing.JButton jButtonEkle;
    private javax.swing.JButton jButtonPingAta;
    private javax.swing.JButton jButtonSifirla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCihazinIPAdresi;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAgaBagliCihazlar;
    private javax.swing.JTextField jTextFieldHostAddressEkleme;
    private javax.swing.JTextField jTextFieldHostNameEkleme;
    private javax.swing.JTextField jTextFieldPingAtma;
    // End of variables declaration//GEN-END:variables
}
